package eu.nebulouscloud.exn.settings

import org.aeonbits.owner.Config
import org.aeonbits.owner.Config.Key
import org.aeonbits.owner.Config.Sources
import org.aeonbits.owner.Config.DefaultValue

/**
 *
 * This class provides the configuration requirements
 * for connecting to the broker and instantiating the
 * connector.
 *
 * These properties can be read either
 *
 * A file in the root path of the application `exn.properties`
 * A classpath resource `exn.properties`
 * Java -D properties
 * Environment variables
 */
@Sources([
    "file:./exn.properties",
    "classpath:exn.properties",
    "system:properties",
    "system:env"
])
public interface ExnConfig extends Config {

    /**
     * This is the base name of the addresses which
     * will be generated by the consumers and producers
     * @return
     */
    @Key("exn.basename")
    @DefaultValue("eu.nebulouscloud")
    String baseName()

    /**
     * This is the default interval of the Health publisher
     * @return
     */
    @Key("exn.health.timeout")
    @DefaultValue("15")
    Integer healthTimeout()

    /**
     * This is the url of the broker
     * @return
     */
    @Key("broker.url")
    String url()

    /**
     * This is the port of the broker
     * @return
     */
    @Key("broker.port")
    int port();

    /**
     * This is the username required to log into
     * @return
     */
    @Key("broker.username")
    String username()

    /**
     * This is the password required to log into
     * @return
     */
    @Key("broker.password")
    String password()
}

